// SkateGoals Phase B — one goal system, weekly review, competition prep, voice capture.
// EN and BG both written natively for a figure-skating environment.
export type PhaseBEntry = { en: string; bg: string };

export const PHASEB_DICT: Record<string, PhaseBEntry> = {
  // ── Voice capture ──
  'voice.start':     { en: 'Speak instead of typing', bg: 'Кажи го, вместо да пишеш' },
  'voice.stop':      { en: 'Stop listening', bg: 'Спри слушането' },
  'voice.listening': { en: 'Listening…', bg: 'Слушам…' },
  'voice.denied':    { en: 'Microphone access is off. Type instead.', bg: 'Достъпът до микрофона е спрян. Напиши го.' },
  'voice.failed':    { en: 'Voice did not work here. Type instead.', bg: 'Гласът не сработи. Напиши го.' },
  'voice.nospeech':  { en: 'Nothing was picked up. Try again.', bg: 'Нищо не се чу. Пробвай пак.' },
  'voice.hint': {
    en: 'Voice becomes editable text. Audio is not stored.',
    bg: 'Гласът се превръща в текст за редакция. Аудиото не се пази.',
  },

  // ── Goals (one system) ──
  'gb.title':        { en: 'Goals', bg: 'Цели' },
  'gb.sub':          { en: 'Season goal → this week’s focus → next action.', bg: 'Цел за сезона → фокус за седмицата → следваща стъпка.' },
  'gb.season':       { en: 'Season goal', bg: 'Цел за сезона' },
  'gb.seasonEmpty':  { en: 'No season goal yet. Add the result or standard you are working toward.', bg: 'Още няма цел за сезона. Добави резултата или стандарта, към който работиш.' },
  'gb.seasonSet':    { en: 'Set season goal', bg: 'Задай цел за сезона' },
  'gb.cycle':        { en: 'This week', bg: 'Тази седмица' },
  'gb.cycleEmpty':   { en: 'Nothing set for this week yet.', bg: 'Още няма нищо за тази седмица.' },
  'gb.cycleSet':     { en: 'Set this week’s focus', bg: 'Задай фокус за седмицата' },
  'gb.next':         { en: 'Next step', bg: 'Следваща стъпка' },
  'gb.nextEmpty':    { en: 'No next step written down.', bg: 'Няма записана следваща стъпка.' },
  'gb.nextPh':       { en: 'e.g. review the short-program feedback before Tuesday', bg: 'напр. преглед на обратната връзка за кратката програма преди вторник' },
  'gb.titleLabel':   { en: 'Goal', bg: 'Цел' },
  'gb.titlePh':      { en: 'e.g. deliver a consistent short program in competition', bg: 'напр. стабилна кратка програма на състезание' },
  'gb.whyLabel':     { en: 'Why it matters', bg: 'Защо е важно' },
  'gb.whyPh':        { en: 'Optional — what this changes for you', bg: 'По избор — защо тази цел е важна за теб' },
  'gb.dateLabel':    { en: 'Target date', bg: 'Целева дата' },
  'gb.save':         { en: 'Save', bg: 'Запази' },
  'gb.cancel':       { en: 'Cancel', bg: 'Отказ' },
  'gb.edit':         { en: 'Edit', bg: 'Редакция' },
  'gb.delete':       { en: 'Delete', bg: 'Изтрий' },
  'gb.done':         { en: 'Mark as reached', bg: 'Отбележи като постигната' },
  'gb.reopen':       { en: 'Reopen', bg: 'Върни в работа' },
  'gb.archive':      { en: 'Reached goals', bg: 'Постигнати цели' },
  'gb.compContext':  { en: 'Competition prep', bg: 'Подготовка за старт' },
  'gb.reviewCta':    { en: 'Weekly review', bg: 'Преглед на седмицата' },
  'gb.reviewSub':    { en: 'Look back at the week and set next week’s focus', bg: 'Погледни седмицата и задай фокуса за следващата' },
  'gb.focusSynced':  { en: 'This is what Today shows you.', bg: 'Това виждаш и в „Днес“.' },
  'gb.newGoal':      { en: 'New goal', bg: 'Нова цел' },
  'gb.other':        { en: 'Other goals', bg: 'Други цели' },
  'gb.otherAdd':     { en: 'Add another goal', bg: 'Добави още една цел' },

  // ── Weekly review ──
  'wr.title':     { en: 'Weekly review', bg: 'Преглед на седмицата' },
  'wr.sub':       { en: 'Review what actually happened this week, then choose one focus for the next.', bg: 'Виж какво реално се случи тази седмица и избери един фокус за следващата.' },
  'wr.glance':    { en: 'This week', bg: 'Тази седмица' },
  'wr.sessions':  { en: 'sessions', bg: 'тренировки' },
  'wr.onIce':     { en: 'on ice', bg: 'на лед' },
  'wr.offIce':    { en: 'off ice', bg: 'суха тренировка' },
  'wr.minutes':   { en: 'min total', bg: 'мин общо' },
  'wr.themes':    { en: 'Worked on', bg: 'Работено по' },
  'wr.reflections': { en: 'post-training notes', bg: 'записи след тренировка' },
  'wr.currentFocus': { en: 'Focus you set', bg: 'Фокусът, който зададе' },
  'wr.empty':     { en: 'No sessions are logged this week. You can still review what you remember.', bg: 'Няма записани тренировки тази седмица. Можеш да прегледаш това, което помниш.' },
  'wr.q1':        { en: 'What improved or became more consistent?', bg: 'Какво се подобри или стана по-постоянно?' },
  'wr.q1ph':      { en: 'An element, a section of the program, how you handled a session…', bg: 'Елемент, част от програмата, как се справи с тренировка…' },
  'wr.q2':        { en: 'What pattern made training harder?', bg: 'Какъв повтарящ се проблем затрудни тренировките?' },
  'wr.q2ph':      { en: 'Timing, attention, recovery, competition pressure…', bg: 'Тайминг, внимание, възстановяване, напрежение преди старт…' },
  'wr.q3':        { en: 'One focus for next week', bg: 'Един фокус за следващата седмица' },
  'wr.q3ph':      { en: 'One priority that fits the plan you have with your coach', bg: 'Един приоритет, който е част от плана с треньора' },
  'wr.confirm':   { en: 'This becomes your focus on Today and in Goals.', bg: 'Това става фокусът ти в „Днес“ и в „Цели“.' },
  'wr.save':      { en: 'Save review', bg: 'Запази прегледа' },
  'wr.saving':    { en: 'Saving…', bg: 'Записвам…' },
  'wr.saved':     { en: 'Review saved. Next week’s focus is set.', bg: 'Прегледът е записан. Фокусът за следващата седмица е зададен.' },
  'wr.close':     { en: 'Not now', bg: 'Не сега' },
  'wr.due':       { en: 'Weekly review', bg: 'Преглед на седмицата' },
  'wr.dueSub':    { en: 'Close the week and pick next week’s focus', bg: 'Затвори седмицата и избери фокуса за следващата' },
  'wr.doneWeek':  { en: 'Review done for this week', bg: 'Прегледът за тази седмица е готов' },
  'wr.needFocus': { en: 'Write one focus for next week first.', bg: 'Първо напиши един фокус за следващата седмица.' },

  // ── Competition prep (phase aware) ──
  'cp.title':      { en: 'Competition prep', bg: 'Подготовка за старт' },
  'cp.close':      { en: 'Close', bg: 'Затвори' },
  'cp.inDays':     { en: 'days to go', bg: 'дни до старта' },
  'cp.tomorrow':   { en: 'Competition tomorrow', bg: 'Старт утре' },
  'cp.today':      { en: 'Competition today', bg: 'Старт днес' },
  'cp.past':       { en: 'After the competition', bg: 'След старта' },
  'cp.noDate':     { en: 'Preparing for a start', bg: 'Подготовка преди старт' },
  'cp.todayCard':  { en: 'Competition prep', bg: 'Подготовка за старт' },
  'cp.open':       { en: 'Open prep', bg: 'Отвори подготовката' },

  'cp.week.head':  { en: 'What is yours to control', bg: 'Какво зависи от теб' },
  'cp.week.intro': { en: 'Training belongs to you and your coach. This part is about being clear on the plan and on what you can decide yourself.', bg: 'Тренировките са между теб и треньора ти. Тук говорим за яснота по плана и за нещата, които зависят от теб.' },
  'cp.week.i1':    { en: 'You know the plan you agreed with your coach for these weeks', bg: 'Знаеш плана, който сте уговорили с треньора за тези седмици' },
  'cp.week.i2':    { en: 'Choose one or two familiar process cues', bg: 'Избери една-две познати кратки насоки' },
  'cp.week.i3':    { en: 'Competition day logistics and timing are confirmed', bg: 'Логистиката и часовете за деня на старта са уточнени' },
  'cp.week.i4':    { en: 'Keep familiar routines instead of adding something new', bg: 'Следвай познатите рутини, без да добавяш нещо ново' },
  'cp.week.i5':    { en: 'Note what you want to ask your coach', bg: 'Запиши какво искаш да питаш треньора си' },
  'cp.week.ai':    { en: 'Organize priorities with AI Coach', bg: 'Подреди приоритетите с AI Coach' },
  'cp.week.aiMsg': { en: 'I have a competition coming up. Help me organize my priorities around the plan I already have with my coach.', bg: 'Скоро имам старт. Помогни ми да подредя приоритетите около плана, който вече имам с треньора.' },

  'cp.eve.head':   { en: 'Tomorrow: routine, logistics, focus', bg: 'Утре: рутина, логистика, фокус' },
  'cp.eve.intro':  { en: 'Use a familiar mental routine, confirm the logistics, and keep tomorrow clear.', bg: 'Прегледай познатата ментална рутина, уточни логистиката и внеси яснота за утрешния ден.' },
  'cp.eve.i1':     { en: 'Check your gear, documents, music, schedule, and travel details', bg: 'Провери екипировката, документите, музиката, графика и пътуването' },
  'cp.eve.i2':     { en: 'Know your times: warm-up, six-minute warm-up, start number', bg: 'Знаеш часовете: загрявка, шестминутка, стартов номер' },
  'cp.eve.i3':     { en: 'Write one or two familiar focus cues for the program', bg: 'Запиши една-две познати насоки за фокус в програмата' },
  'cp.eve.i4':     { en: 'Check the familiar pre-start routine that already works for you and fits your coach’s plan', bg: 'Прегледай познатата рутина преди старт, която вече ти върши работа и е съобразена с плана на треньора' },
  'cp.eve.cue':    { en: 'Your focus cues for tomorrow', bg: 'Кратки насоки за утре' },
  'cp.eve.cuePh':  { en: 'e.g. my tempo · next task · reset', bg: 'напр. моето темпо · следващата задача · рестарт' },
  'cp.eve.ai':     { en: 'Nerves before tomorrow? Sport Psychology', bg: 'Нерви за утре? Спортна психология' },
  'cp.eve.aiMsg':  { en: 'I compete tomorrow and I can feel the tension.', bg: 'Утре имам старт и усещам напрежение.' },

  'cp.day.head':   { en: 'Short reset', bg: 'Кратък рестарт' },
  'cp.day.intro':  { en: 'If useful, take a few slower breaths, then return to one familiar cue. Stop at any time.', bg: 'Ако ти е полезно, направи няколко по-бавни вдишвания и се върни към една позната насока. Спри по всяко време.' },
  'cp.day.breathe':{ en: 'Optional: breathe with the circle', bg: 'По избор: дишай с кръга' },
  'cp.day.inhale': { en: 'In', bg: 'Вдишай' },
  'cp.day.exhale': { en: 'Out, slower', bg: 'Издишай, по-бавно' },
  'cp.day.done':   { en: 'Complete', bg: 'Готово' },
  'cp.day.skip':   { en: 'Skip the breathing', bg: 'Пропусни дишането' },
  'cp.day.cue':    { en: 'One familiar cue for the ice', bg: 'Една позната насока за леда' },
  'cp.day.ai':     { en: 'Talk it through: Sport Psychology', bg: 'Поговори за напрежението: Спортна психология' },
  'cp.day.aiMsg':  { en: 'I skate today and I want to settle down before I go on.', bg: 'Днес се състезавам и искам да се успокоя, преди да изляза.' },

  'cp.after.head': { en: 'Short debrief', bg: 'Кратък разбор' },
  'cp.after.intro':{ en: 'Write it down while it is fresh. Facts first, judgement later.', bg: 'Запиши го, докато е прясно. Първо фактите, оценките после.' },
  'cp.after.q1':   { en: 'What did you do well, regardless of the result?', bg: 'Какво направи добре, независимо от резултата?' },
  'cp.after.q2':   { en: 'What was different from training?', bg: 'Какво беше различно от тренировка?' },
  'cp.after.q3':   { en: 'What do you take into the next weeks?', bg: 'Какво взимаш в следващите седмици?' },
  'cp.after.save': { en: 'Save debrief', bg: 'Запиши разбора' },
  'cp.after.saved':{ en: 'Debrief saved.', bg: 'Разборът е записан.' },

  // ── Progress signals ──
  'ps.title':      { en: 'Signals', bg: 'Показатели' },
  'ps.weekSess':   { en: 'Sessions this week', bg: 'Тренировки тази седмица' },
  'ps.weekRefl':   { en: 'Post-training notes this week', bg: 'Записи след тренировка тази седмица' },
  'ps.reviews':    { en: 'Reviews in the last 4 weeks', bg: 'Прегледи за последните 4 седмици' },
  'ps.focus':      { en: 'Current focus', bg: 'Текущ фокус' },
  'ps.focusNone':  { en: 'Not set', bg: 'Няма зададен' },
  'ps.themes':     { en: 'Most worked on this week', bg: 'Най-много работено тази седмица' },
  'ps.readonly':   { en: 'Everything here comes from your own entries. Nothing to fill in.', bg: 'Всичко тук идва от записите ти. Няма какво да попълваш.' },
  'ps.goal':       { en: 'Season goal', bg: 'Цел за сезона' },
  'ps.goalNone':   { en: 'Not set', bg: 'Няма зададена' },
  'ps.week':       { en: 'This week', bg: 'Тази седмица' },

  // ── Save state ──
  'wr.saveFailed': { en: 'Saving did not go through. Your text is still here — try again.', bg: 'Записът не мина. Текстът ти е тук — пробвай пак.' },
  'cp.day.start':  { en: 'Start breathing', bg: 'Започни дишането' },
  'a.rf.needFocus': { en: 'Add a focus for next training to save, or skip for now.', bg: 'Добави фокус за следващата тренировка, за да запишеш, или пропусни засега.' },
  'a.tr.saveFailed': { en: 'The session did not save. Everything you entered is still here — try again.', bg: 'Тренировката не се записа. Всичко въведено е тук — пробвай пак.' },
  'gb.saveFailed': { en: 'Saving did not go through. Your text is still here — try again.', bg: 'Записът не мина. Текстът ти е тук — пробвай пак.' },
};
