// SkateGoals Phase B — one goal system, weekly review, competition prep, voice capture.
// EN and BG both written natively for a figure-skating environment.
export type PhaseBEntry = { en: string; bg: string };

export const PHASEB_DICT: Record<string, PhaseBEntry> = {
  // ── Voice capture ──
  'voice.start':     { en: 'Speak instead of typing', bg: 'Кажи го, вместо да пишеш' },
  'voice.stop':      { en: 'Stop recording', bg: 'Спри записа' },
  'voice.listening': { en: 'Listening…', bg: 'Слушам…' },
  'voice.denied':    { en: 'Microphone access is off. Type instead.', bg: 'Достъпът до микрофона е спрян. Напиши го.' },
  'voice.failed':    { en: 'Voice did not work here. Type instead.', bg: 'Гласът не сработи. Напиши го.' },
  'voice.nospeech':  { en: 'Nothing was picked up. Try again.', bg: 'Нищо не се чу. Пробвай пак.' },
  'voice.hint': {
    en: 'Speech becomes text you can edit before saving. SkateGoals does not keep the audio; your browser or device handles the recognition and may process it on its servers.',
    bg: 'Говорът се превръща в текст, който можеш да редактираш преди запис. SkateGoals не пази аудиото; разпознаването е на браузъра или устройството ти и може да минава през техни сървъри.',
  },

  // ── Goals (one system) ──
  'gb.title':        { en: 'Goals', bg: 'Цели' },
  'gb.sub':          { en: 'Season goal, what you are working on now, and the next step.', bg: 'Цел за сезона, по какво работиш сега и коя е следващата стъпка.' },
  'gb.season':       { en: 'Season goal', bg: 'Цел за сезона' },
  'gb.seasonEmpty':  { en: 'No season goal yet. Name the one thing this season is about.', bg: 'Още няма цел за сезона. Кажи за какво е този сезон.' },
  'gb.seasonSet':    { en: 'Set season goal', bg: 'Задай цел за сезона' },
  'gb.cycle':        { en: 'This week', bg: 'Тази седмица' },
  'gb.cycleEmpty':   { en: 'Nothing set for this week yet.', bg: 'Още няма нищо за тази седмица.' },
  'gb.cycleSet':     { en: 'Set this week’s focus', bg: 'Задай фокус за седмицата' },
  'gb.next':         { en: 'Next step', bg: 'Следваща стъпка' },
  'gb.nextEmpty':    { en: 'No next step written down.', bg: 'Няма записана следваща стъпка.' },
  'gb.nextPh':       { en: 'e.g. two clean run-throughs of the short program', bg: 'напр. две чисти прокарвания на кратката програма' },
  'gb.titleLabel':   { en: 'Goal', bg: 'Цел' },
  'gb.titlePh':      { en: 'e.g. consistent double axel in the program', bg: 'напр. стабилен двоен аксел в програмата' },
  'gb.whyLabel':     { en: 'Why it matters', bg: 'Защо е важно' },
  'gb.whyPh':        { en: 'Optional — what this changes for you', bg: 'По избор — какво ти променя това' },
  'gb.dateLabel':    { en: 'Target date', bg: 'Целева дата' },
  'gb.save':         { en: 'Save', bg: 'Запиши' },
  'gb.cancel':       { en: 'Cancel', bg: 'Отказ' },
  'gb.edit':         { en: 'Edit', bg: 'Редакция' },
  'gb.delete':       { en: 'Delete', bg: 'Изтрий' },
  'gb.done':         { en: 'Mark as reached', bg: 'Отбележи като постигната' },
  'gb.reopen':       { en: 'Reopen', bg: 'Върни в работа' },
  'gb.archive':      { en: 'Reached goals', bg: 'Постигнати цели' },
  'gb.compContext':  { en: 'Competition context', bg: 'Контекст: старт' },
  'gb.reviewCta':    { en: 'Weekly review', bg: 'Седмичен преглед' },
  'gb.reviewSub':    { en: 'Look back at the week and set next week’s focus', bg: 'Погледни седмицата и задай фокуса за следващата' },
  'gb.focusSynced':  { en: 'This is what Today shows you.', bg: 'Това виждаш и в „Днес“.' },
  'gb.newGoal':      { en: 'New goal', bg: 'Нова цел' },
  'gb.other':        { en: 'Other goals', bg: 'Други цели' },
  'gb.otherAdd':     { en: 'Add another goal', bg: 'Добави още една цел' },

  // ── Weekly review ──
  'wr.title':     { en: 'Weekly review', bg: 'Седмичен преглед' },
  'wr.sub':       { en: 'Three or four minutes. Look at the week, then decide next week’s focus.', bg: 'Три-четири минути. Погледни седмицата и реши фокуса за следващата.' },
  'wr.glance':    { en: 'This week', bg: 'Тази седмица' },
  'wr.sessions':  { en: 'sessions', bg: 'тренировки' },
  'wr.onIce':     { en: 'on ice', bg: 'на лед' },
  'wr.offIce':    { en: 'off ice', bg: 'суха подготовка' },
  'wr.minutes':   { en: 'min total', bg: 'мин общо' },
  'wr.themes':    { en: 'Worked on', bg: 'Работено по' },
  'wr.reflections': { en: 'reflections written', bg: 'записани рефлексии' },
  'wr.currentFocus': { en: 'Focus you set', bg: 'Фокусът, който зададе' },
  'wr.empty':     { en: 'Nothing logged this week — you can still write the review.', bg: 'Няма записани тренировки тази седмица — прегледът пак има смисъл.' },
  'wr.q1':        { en: 'What moved forward?', bg: 'Какво тръгна напред?' },
  'wr.q1ph':      { en: 'An element, a section of the program, how you handled a session…', bg: 'Елемент, част от програмата, как се справи с тренировка…' },
  'wr.q2':        { en: 'What kept getting in the way?', bg: 'Какво постоянно пречеше?' },
  'wr.q2ph':      { en: 'Something technical, timing, energy, nerves…', bg: 'Техника, време, енергия, нерви…' },
  'wr.q3':        { en: 'One focus for next week', bg: 'Един фокус за следващата седмица' },
  'wr.q3ph':      { en: 'Keep it to one thing you can work on every session', bg: 'Само едно нещо, по което да работиш всяка тренировка' },
  'wr.confirm':   { en: 'This becomes your focus on Today and in Goals.', bg: 'Това става фокусът ти в „Днес“ и в „Цели“.' },
  'wr.save':      { en: 'Save review', bg: 'Запиши прегледа' },
  'wr.saving':    { en: 'Saving…', bg: 'Записвам…' },
  'wr.saved':     { en: 'Review saved. Next week’s focus is set.', bg: 'Прегледът е записан. Фокусът за следващата седмица е зададен.' },
  'wr.close':     { en: 'Not now', bg: 'Не сега' },
  'wr.due':       { en: 'Weekly review', bg: 'Седмичен преглед' },
  'wr.dueSub':    { en: 'Close the week and pick next week’s focus', bg: 'Затвори седмицата и избери фокуса за следващата' },
  'wr.doneWeek':  { en: 'Review done for this week', bg: 'Прегледът за тази седмица е готов' },
  'wr.needFocus': { en: 'Write one focus for next week first.', bg: 'Първо напиши един фокус за следващата седмица.' },

  // ── Competition prep (phase aware) ──
  'cp.title':      { en: 'Competition prep', bg: 'Подготовка за старт' },
  'cp.close':      { en: 'Close', bg: 'Затвори' },
  'cp.inDays':     { en: 'days to go', bg: 'дни до старта' },
  'cp.tomorrow':   { en: 'Competition tomorrow', bg: 'Старт утре' },
  'cp.today':      { en: 'Competition today', bg: 'Старт днес' },
  'cp.past':       { en: 'After the competition', bg: 'След старта' },
  'cp.noDate':     { en: 'Preparing for a start', bg: 'Подготовка преди старт' },
  'cp.todayCard':  { en: 'Competition prep', bg: 'Подготовка за старт' },
  'cp.open':       { en: 'Open prep', bg: 'Отвори подготовката' },

  'cp.week.head':  { en: 'Control what you can control', bg: 'Контролирай това, което зависи от теб' },
  'cp.week.intro': { en: 'The weeks before a start are for the things you decide: what you rehearse, how you sleep, how you warm up.', bg: 'Седмиците преди старт са за нещата, които ти решаваш: какво прокарваш, как спиш, как загряваш.' },
  'cp.week.i1':    { en: 'Run the program in full, in competition order', bg: 'Прокарай програмата цяла, в състезателен ред' },
  'cp.week.i2':    { en: 'Rehearse the entry into your hardest element, not just the element', bg: 'Репетирай входа към най-трудния елемент, не само елемента' },
  'cp.week.i3':    { en: 'Keep your warm-up the same as the one you will use on the day', bg: 'Дръж загрявката същата като тази в деня на старта' },
  'cp.week.i4':    { en: 'Plan sleep and travel now, so the last days are quiet', bg: 'Планирай съня и пътуването сега, за да са спокойни последните дни' },
  'cp.week.ai':    { en: 'Plan the weeks with AI Coach', bg: 'Планирай седмиците с AI треньора' },
  'cp.week.aiMsg': { en: 'I have a competition coming up. Help me plan the training weeks before it.', bg: 'Скоро имам старт. Помогни ми да разпределя тренировъчните седмици преди него.' },

  'cp.eve.head':   { en: 'Tomorrow: routine, logistics, cues', bg: 'Утре: рутина, логистика, думи-опори' },
  'cp.eve.intro':  { en: 'The day before is not for new work. It is for making tomorrow predictable.', bg: 'Денят преди старта не е за нова работа. Той е за да направиш утрешния ден предвидим.' },
  'cp.eve.i1':     { en: 'Bag packed: skates, laces, tights, music, water, snack', bg: 'Приготвен сак: кънки, връзки, чорапогащник, музика, вода, храна' },
  'cp.eve.i2':     { en: 'Know your times: warm-up, six-minute warm-up, start number', bg: 'Знаеш часовете: загрявка, шестминутка, стартов номер' },
  'cp.eve.i3':     { en: 'Write the two or three cues you will use in the program', bg: 'Запиши двете-трите думи, които ще ползваш в програмата' },
  'cp.eve.i4':     { en: 'Same evening routine as before a normal training day', bg: 'Същата вечерна рутина като преди обикновен тренировъчен ден' },
  'cp.eve.cue':    { en: 'Your cues for tomorrow', bg: 'Твоите думи-опори за утре' },
  'cp.eve.cuePh':  { en: 'e.g. long edges · soft knees · my tempo', bg: 'напр. дълги ръбове · меки колене · моето темпо' },
  'cp.eve.ai':     { en: 'Nerves before tomorrow? Sport Psychology', bg: 'Нерви за утре? Спортна психология' },
  'cp.eve.aiMsg':  { en: 'I compete tomorrow and I am nervous about it.', bg: 'Утре се състезавам и съм изнервен/а от това.' },

  'cp.day.head':   { en: 'Short reset', bg: 'Кратък рестарт' },
  'cp.day.intro':  { en: 'Slow the breath, then hold one cue. Nothing else needs deciding now.', bg: 'Забави дишането и задръж една дума. Нищо друго не се решава сега.' },
  'cp.day.breathe':{ en: 'Breathe with the circle', bg: 'Дишай с кръга' },
  'cp.day.inhale': { en: 'In', bg: 'Вдишай' },
  'cp.day.hold':   { en: 'Hold', bg: 'Задръж' },
  'cp.day.exhale': { en: 'Out', bg: 'Издишай' },
  'cp.day.done':   { en: 'Steady', bg: 'Спокойно' },
  'cp.day.cue':    { en: 'The one cue you take on the ice', bg: 'Думата, с която излизаш на лед' },
  'cp.day.ai':     { en: 'Talk it through: Sport Psychology', bg: 'Кажи го на глас: Спортна психология' },
  'cp.day.aiMsg':  { en: 'I skate today and I want to settle down before I go on.', bg: 'Днес се състезавам и искам да се успокоя, преди да изляза.' },

  'cp.after.head': { en: 'Short debrief', bg: 'Кратък разбор' },
  'cp.after.intro':{ en: 'Write it down while it is fresh. Facts first, judgement later.', bg: 'Запиши го, докато е прясно. Първо фактите, оценките после.' },
  'cp.after.q1':   { en: 'What did you do well, regardless of the result?', bg: 'Какво направи добре, независимо от резултата?' },
  'cp.after.q2':   { en: 'What was different from training?', bg: 'Какво беше различно от тренировка?' },
  'cp.after.q3':   { en: 'What do you take into the next weeks?', bg: 'Какво взимаш в следващите седмици?' },
  'cp.after.save': { en: 'Save debrief', bg: 'Запиши разбора' },
  'cp.after.saved':{ en: 'Debrief saved.', bg: 'Разборът е записан.' },

  // ── Progress signals ──
  'ps.title':      { en: 'Signals', bg: 'Показатели' },
  'ps.weekSess':   { en: 'Sessions this week', bg: 'Тренировки тази седмица' },
  'ps.weekRefl':   { en: 'Reflections this week', bg: 'Рефлексии тази седмица' },
  'ps.reviews':    { en: 'Weekly reviews (last 4 weeks)', bg: 'Седмични прегледи (последните 4)' },
  'ps.focus':      { en: 'Current focus', bg: 'Текущ фокус' },
  'ps.focusNone':  { en: 'Not set', bg: 'Няма зададен' },
  'ps.themes':     { en: 'Most worked on this week', bg: 'Най-много работено тази седмица' },
  'ps.readonly':   { en: 'Everything here comes from what you logged. Nothing to fill in.', bg: 'Всичко тук идва от това, което си записал/а. Няма какво да попълваш.' },
};
